apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: dockerimage
        image: rekha91/proj-cicd:latest
        ports:
        - containerPort: 8000
        
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  selector:
    app: nginx
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
       
        
        
